#!/usr/bin/env bash
# Displaying the information on the server
custom_info_for_domain() {
    local custom_domain_var="$1"
    local custom_subdomain_var="$2"
    local custom_line_var
    custom_line_var=$(dig "$custom_subdomain_var"."$custom_domain_var" | awk '/ANSWER SECTION:/ {getline; print; getline; print}')
    echo "$custom_subdomain_var $custom_line_var" | awk '{printf "The subdomain %s is a %s record and points to %s\n", $1, $2, $3}'
}

if [ "$#" -eq 1 ]; then
    custom_info_for_domain "$1" "www"
    custom_info_for_domain "$1" "lb-01"
    custom_info_for_domain "$1" "web-01"
    custom_info_for_domain "$1" "web-02"
elif [ "$#" -eq 2 ]; then
    custom_info_for_domain "$1" "$2"
fi
