#!/usr/bin/env bash
# Displaying the information on the server

if [ "$#" -eq 1 ]; then
    echo "$(dig www.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain www is a "$4" record and points to "$5}')"
    echo "$(dig lb-01.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain lb-01 is a "$4" record and points to "$5}')"
    echo "$(dig web-01.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-01 is a "$4" record and points to "$5}')"
    echo "$(dig web-02.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain web-02 is a "$4" record and points to "$5}')"
elif [ "$#" -eq 2 ]; then
    custom_subdomain_var=$2
    echo "$(dig $custom_subdomain_var.$1 | awk '/ANSWER SECTION:/ {getline; print "The subdomain '"$custom_subdomain_var"' is a "$4" record and points to "$5}')"
fi
