#!/usr/bin/env bash
# Instaalling  nginx
sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 22
sudo ufw allow 80
sudo ufw --force enable
echo "Hello World!" > sudo tee /var/www/html/index.html
sudo service nginx restart
