#!/usr/bin/env bash
# Dealing with start|stop|restart
function start
{
    ./manage_my_process &
    echo $!>/var/run/my_process.pid
    echo "manage_my_process started"
}

function stop
{
    kill $(cat /var/run/my_process.pid)
    rm -f /var/run/my_process.pid
    echo "manage_my_process stopped"
}

function restart
{
    stop
    sleep 1
    start
    echo "manage_my_process restarted"
}

case "$1" in
    "start")
        start
        ;;
    "stop")
        stop
        ;;
    "restart")
        restart
        ;;
    *)
    echo "Usage: manage_my_process {start|stop|restart}"
    ;;
esac
