#!/usr/bin/env bash
# Displaying the content of /etc/passwd

data="/etc/passwd"
awk -F: '{print "The user "$1" is part of the "$4" gang, lives in "$6" and rides "$7". "$3" place is protected by the passcode "$2", more info about the user here: "$5}' $data
