#!/usr/bin/env bash
# Print the world "Best School" ten times, 9nth display "Hi"

x=0
while [ $x -lt 10 ]
do
    if [ $x -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    x=$((x + 1))
done
