#!/usr/bin/env bash
# Display a clock with twelve format

x=0
while [ "$x" -le 12 ]
do
    echo "Hour: $x"
    i=1
    while [ "$i" -le 59 ]
    do
        echo "$i"
        i=$((i + 1))
    done
    x=$((x + 1))
done
