#!/usr/bin/env bash
# Replacing the Ip Address of the local host
# Appending ip address to the existing hostname

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
